import Head from 'next/head'
import { useEffect, useContext } from 'react'
import Link from 'next/dist/client/link'
import { useRouter } from 'next/router'
import styles from '../../styles/Login.module.css'
import Title from '../../components/view/title'
import Form from '../../components/form/Form'
import { AuthContext } from '../../components/auth/AuthContext'

export default function SignUpSubmit() {
  const { currentUser, setCurrentUser }: any = useContext(AuthContext)
  const router = useRouter()

  // useEffect(() => {
  //   if (sendEmail == undefined) router.replace('/')
  // }, [])
  return (
    <>
      <Head>
        <title>Goodsist イベントのグッズ代が計算できるWEBアプリ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width,initial-scale=1.0,maximum-scale=1.0' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap&text=Goodsist'
          rel='stylesheet'
        />
      </Head>

      <main className={styles.main}>
        <Title title='登録完了' />
        <Form>
          <div className={styles.send_email_address}>登録が完了しました。</div>
          <div className={styles.send_email_text}>
            以下の情報で会員登録が完了しました。
            <br />
            <br />
            24時間経過すると確認メールは無効となりますので、もう一度最初からお手続きください。
          </div>

          <div className={styles.link_return}>
            <Link href='/'>
              <a target='_blank'>トップページ</a>
            </Link>
          </div>
        </Form>
      </main>
    </>
  )
}
