import Link from 'next/link'
import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState, useEffect, useRef, useCallback, useContext } from 'react'
import { supabase } from '../../components/supabase'
import styles from '../../styles/Login.module.css'
import { InferGetStaticPropsType, GetStaticPropsContext } from 'next'
import IconTwitter from '../img/icon_twitter.svg'
import IconLine from '../img/line.svg'
import Mail from '../img/mail.svg'
import Yahoo from '../img/yahoo.png'
import Password from '../img/password.svg'
import Google from '../img/google.svg'
import Navbar from '../../components/Navber'
import Image from 'next/image'
import { AuthContext } from '../../components/auth/AuthContext'

type Props = InferGetStaticPropsType<typeof getStaticProps>

type LoginKey = {
  email: string
  password: string
}

export const getStaticProps = async (context: GetStaticPropsContext) => {
  const data = 'テスト'

  return {
    props: { data },
  }
}

const LoginGate = (data: Props) => {
  const { user, session, signOut }: any = useContext(AuthContext)
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const login = async () => {
    const { error, data } = await supabase.auth.signIn({ email, password })
    if (error) {
      console.log({ error })
    } else {
      console.log({ data })
    }
  }

  const signup = async () => {
    const { error } = await supabase.auth.signUp({ email, password })
    if (error) {
      console.log({ error })
    } else {
      console.log({ data })
    }
  }

  const [selectLogin, setSelectLogin] = useState([
    styles.select_login_active,
    styles.select_register,
    styles.select_underbar_login,
  ])

  const changeSelectLogin = (select: string) => {
    if (select == 'register') {
      const newSelectLogin = [
        styles.select_login,
        styles.select_register_active,
        styles.select_underbar_register,
      ]
      setSelectLogin(newSelectLogin)
    } else if (select == 'login') {
      const newSelectLogin = [
        styles.select_login_active,
        styles.select_register,
        styles.select_underbar_login,
      ]
      setSelectLogin(newSelectLogin)
    }
  }

  return (
    <>
      <Head>
        <title>Goodsist イベントのグッズ代が計算できるWEBアプリ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width,initial-scale=1.0,maximum-scale=1.0' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap&text=Goodsist'
          rel='stylesheet'
        />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <div className={styles.content_title}>
          <span>ログイン / 新規登録{user ? user.user_name : ''}</span>
        </div>
        <div className={styles.card}>
          <div className={styles.select_login_container}>
            <button className={selectLogin[0]} onClick={() => changeSelectLogin('login')}>
              ログイン
            </button>
            <button className={selectLogin[1]} onClick={() => changeSelectLogin('register')}>
              <Link href={'/signup'}>
                <a>新規登録</a>
              </Link>
            </button>
          </div>
          <div className={styles.select_underbar_container}>
            <div className={selectLogin[2]}></div>
          </div>
          <div className={styles.form_container}>
            <button className={styles.btn_login_twitter}>
              Twitterでログイン
              <span>
                <IconTwitter />
              </span>
            </button>
            <button className={styles.btn_login_line}>
              LINEでログイン
              <span>
                <IconLine />
              </span>
            </button>
            <button className={styles.btn_login_yahoo}>
              Yahoo! JAPANでログイン
              <span>
                <img src='../../images/yahoo.png' width='35px' height='35px' />
              </span>
            </button>
            <button className={styles.btn_login_google}>
              Googleでログイン
              <span>
                <img src='../../images/google.svg' width='26px' height='26px' />
              </span>
            </button>
          </div>
          <hr className={styles.space_bar} />

          <div className={styles.form_container}>
            {email}
            <span className={styles.input_mail_container}>
              <input
                className={styles.input_mail}
                type='text'
                name='email'
                placeholder='メールアドレス'
                onChange={(e) => setEmail(e.target.value)}
              />
              <span>
                <Mail />
              </span>
            </span>
            <div className={styles.input_error}></div>
            {password}
            <span className={styles.input_password_container}>
              <input
                className={styles.input_password}
                type='password'
                name='password'
                placeholder='パスワード'
                onChange={(e) => setPassword(e.target.value)}
              />
              <span>
                <Password />
              </span>
            </span>
            <div className={styles.input_error}>不正な値です。</div>
            <div className={styles.forgot_password} onClick={() => signOut()}>
              パスワードを忘れた場合
            </div>
            <button className={styles.btn_login_mail} onClick={() => login()}>
              メールアドレスでログイン
              <span>
                <Mail />
              </span>
            </button>
            <button className={styles.btn_login_mail} onClick={() => signup()}>
              メールアドレスで登録
              <span>
                <Mail />
              </span>
            </button>
          </div>

          <div className={styles.terms}>
            <u>利用規約</u>、<u>プライバシーポリシー</u>に同意の上ご利用ください。
          </div>
        </div>
      </main>
    </>
  )
}

export default LoginGate

// 本来は、ここで外部 API などを呼び出してデータを取得する

// const { data, error } = await supabase
//   .from('goods')
//   .select(
//     'goods_id, goods_name, goods_group, goods_type, color, size, price, events(event_id, event_name, first_date, url, contents(content_id, content_name))',
//   )
//   .eq('event_id', event_id)

// const goodsList: Goods[] = []
// data?.map((doc) => {
//   const goods: Goods = {
//     content_id: doc.events.contents.content_id,
//     content_name: doc.events.contents.content_name,
//     event_id: doc.events.event_id,
//     event_name: doc.events.event_name,
//     first_date: doc.events.first_date,
//     url: doc.events.url,
//     goods_id: doc.goods_id,
//     goods_name: doc.goods_name,
//     goods_group: doc.goods_group,
//     goods_type: doc.goods_type,
//     color: doc.color,
//     size: doc.size,
//     price: doc.price,
//     goods_count: 0,
//   }
//   goodsList.push(goods)
// })
