import styles from '../../styles/Login.module.css'
import { AuthContext } from '../../components/auth/AuthContext'
import { ModalContext } from '../../components/modal/ModalContext'
import { useState, useEffect, useContext } from 'react'
import Head from 'next/head'
import Link from 'next/dist/client/link'
import Title from '../../components/view/title'
import Form from '../../components/form/Form'
import InputLabel from '../../components/form/InputLabel'
import InputText from '../../components/form/InputText'
import SubmitButton from '../../components/form/SubmitButton'
import Twitter from '../../components/form/SocialButton'
import Line from '../../components/form/SocialButton'
import { validateEmail, validatePassword } from '../../components/Validation'
import { login } from '../../components/firebase'
import { useRouter } from 'next/router'
import type { GetServerSideProps, NextPage } from 'next'
import nookies from 'nookies'
import { firebaseAdmin } from '../../components/firebaseAdmin'

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const cookies = nookies.get(ctx)
  const session = cookies.session || ''

  //セッションIDを検証して、認証情報を取得する
  const user = await firebaseAdmin
    .auth()
    .verifySessionCookie(session, true)
    .catch(() => null)

  //ログイン済みの場合はマイページへ飛ばす
  if (user) {
    return {
      redirect: {
        destination: '/mypage',
        permanent: false,
      },
    }
  }

  return {
    props: {},
  }
}

const LogIn = () => {
  const { setCurrentUser }: any = useContext(AuthContext)

  const { setOpenClearOverlay }: any = useContext(ModalContext)

  const [email, setEmail] = useState('')
  const [errorEmail, setErrorEmail] = useState('')
  const [validEmail, setValidEmail] = useState(false)
  const [password, setPassword] = useState('')
  const [errorPassword, setErrorPassword] = useState('')
  const [validPassword, setValidPassword] = useState(false)
  const [isSubmit, setIsSubmit] = useState(false)
  const [errorSubmit, setErrorSubmit] = useState('')
  const [isButtonLoading, setIsButtonLoading] = useState(false)

  //メールアドレス入力のエラーチェック
  useEffect(() => {
    const newErrorEmail = validateEmail(email)
    setErrorEmail(newErrorEmail)
    if (email.length > 0 && errorEmail == '') setValidEmail(true)
    else setValidEmail(false)
  }, [email])

  //パスワード入力のエラーチェック
  useEffect(() => {
    const newErrorPassword = validatePassword(password)
    setErrorPassword(newErrorPassword)
    if (password.length > 0 && newErrorPassword == '') setValidPassword(true)
    else setValidPassword(false)
  }, [password])

  //全ての入力のバリデーションがtrueならボタンをアクティブにする
  useEffect(() => {
    if (validEmail && validPassword) setIsSubmit(true)
    else setIsSubmit(false)
  }, [validEmail, validPassword])
  const router = useRouter()

  //「メールアドレスでログイン」ボタンを押下
  const submitLogin = async () => {
    setIsButtonLoading(true)
    setOpenClearOverlay(true)
    setErrorSubmit('')
    const uid = await login(email, password).catch((error) => {
      if (error == 'FirebaseError: Firebase: Error (auth/wrong-password).')
        setErrorSubmit('メールアドレスまたはパスワードが間違っています。')
      else setErrorSubmit('エラーが発生しました。しばらく経ってからもう一度お試しください。')
      return
    })
    if (uid) {
      setCurrentUser(uid)
      router.push('/mypage')
    }
    setIsButtonLoading(false)
    setOpenClearOverlay(false)
  }

  return (
    <>
      <Head>
        <title>Goodsist イベントのグッズ代が計算できるWEBアプリ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width,initial-scale=1.0,maximum-scale=1.0' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap&text=Goodsist'
          rel='stylesheet'
        />
      </Head>

      <main className={styles.main}>
        <Title title='ログイン' />
        <Form>
          <InputLabel label='SNSアカウントでログイン' />
          <Twitter provider='Twitter' type='signin' />
          <Line provider='LINE' type='signin' />
          <InputLabel label='メールアドレスでログイン' />
          <InputText
            valid={validEmail}
            name='email'
            type='text'
            placeholder='メールアドレス'
            onChange={setEmail}
            error={errorEmail}
          />
          <InputText
            valid={validPassword}
            name='password'
            type='password'
            placeholder='パスワード'
            onChange={setPassword}
            error={errorPassword}
          />
          <div className={styles.forgot_password}>
            <Link href='/signup/password'>
              <a>パスワードを忘れた場合</a>
            </Link>
          </div>
          <SubmitButton
            isSubmit={isSubmit}
            isButtonLoading={isButtonLoading}
            type='email'
            title='メールアドレスでログイン'
            onClick={() => submitLogin()}
            error={errorSubmit}
          />
          <Link href='/signup'>
            <a>
              <button className={styles.btn_link_signup}>会員登録はこちら</button>
            </a>
          </Link>
        </Form>
      </main>
    </>
  )
}

export default LogIn
