import { useRouter } from 'next/router'
import { supabase } from '../../../components/supabase'
import Link from 'next/link'
import styles from '../../../styles/Admin.module.css'
import Title from '../../../components/view/title'
import Head from 'next/head'
import { GetServerSideProps } from 'next'
import InputText from '../../../components/form/InputText'
import { useEffect, useState } from 'react'
import AdminHeader from '../../../components/admin/Header'
import AdminLogin from '../../../components/admin/login'
import { ContentsList } from '../../../components/types'

// ページコンポーネントに渡されるデータ
type Props = {
  contentsList: ContentsList[]
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data, error } = await supabase
    .from('contents')
    .select('content_id, content_name')
    .order('content_id', { ascending: false })

  const contentsList: ContentsList[] = []

  data?.map((doc) => {
    const content: ContentsList = {
      content_id: doc.content_id,
      content_name: doc.content_name,
    }
    contentsList.push(content)
  })

  return { props: { contentsList } }
}
export default function Admin({ contentsList }: Props) {
  const router = useRouter()

  console.log(contentsList)

  return (
    <>
      <Head>
        <title>Goods List 管理者ログイン</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width,initial-scale=1.0,maximum-scale=1.0' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap&text=Goodsist'
          rel='stylesheet'
        />
        <link
          href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
          rel='stylesheet'
        ></link>
      </Head>
      <AdminHeader />
      <div className={styles.wrapper_white}>
        <Title title='コンテンツ一覧' />

        <Link href='contents/register'>
          <a>新規登録</a>
        </Link>
        <br />
        <Link href='contents/csv'>
          <a>CSV新規登録</a>
        </Link>
        <ul>
          {contentsList.map((content) => (
            <li>
              {content.content_id} {content.content_name}{' '}
              <Link href={'contents/' + content.content_id}>
                <a>編集</a>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </>
  )
}
