import Link from 'next/link'
import React from 'react'
import { GetStaticProps } from 'next'
/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect, useCallback } from 'react'
import Footer from '../../components/Footer'
import Header from '../../components/Header'
import { supabase } from '../../components/supabase'
import styles from '../../styles/Goods.module.css'
import { GetStaticPaths } from 'next'

class EventInfo {
  content_id: number = 0
  content_name: string = ''
  event_id: number = 0
  event_name: string = ''
  first_date: string = '2000-00-00'
  one_date: boolean = false
  url: string = ''
}

class Goods extends EventInfo {
  goods_id: number = 0
  goods_name: string = ''
  goods_group: number = 0
  goods_type: string = ''
  color: string = ''
  size: string = ''
  price: number = 0
  goods_count: number = 0
}

type PathParams = {
  event_id: string
}

// ページコンポーネントに渡されるデータ
type Props = {
  goodsList: Goods[]
}

export const getStaticPaths: GetStaticPaths<PathParams> = async () => {
  const { data, error } = await supabase.from('events').select('event_id')

  if (!data) {
    throw new Error('エラーです。')
  }
  const paths = data?.map((doc) => ({
    params: {
      event_id: doc.event_id.toString(),
    },
  }))
  console.log(paths)
  return { paths, fallback: false }
}

// この関数がビルド時に呼び出され、戻り値の props の値がページコンポーネントに渡される
export const getStaticProps: GetStaticProps<Props> = async (context) => {
  // 本来は、ここで外部 API などを呼び出してデータを取得する

  const { event_id } = context.params as PathParams

  const { data, error } = await supabase
    .from('goods')
    .select(
      'goods_id, goods_name, goods_group, goods_type, color, size, price, events(event_id, event_name, first_date, one_date, url, contents(content_id, content_name))',
    )
    .eq('event_id', event_id)

  const goodsList: Goods[] = []
  data?.map((doc) => {
    const goods: Goods = {
      content_id: doc.events.contents.content_id,
      content_name: doc.events.contents.content_name,
      event_id: doc.events.event_id,
      event_name: doc.events.event_name,
      first_date: doc.events.first_date,
      one_date: doc.events.one_date,
      url: doc.events.url,
      goods_id: doc.goods_id,
      goods_name: doc.goods_name,
      goods_group: doc.goods_group,
      goods_type: doc.goods_type,
      color: doc.color,
      size: doc.size,
      price: doc.price,
      goods_count: 0,
    }
    goodsList.push(goods)
  })

  // この props プロパティの値がページコンポーネントに渡される
  return { props: { goodsList } }
}

// ページコンポーネントの実装
const Home: React.FC<Props> = ({ goodsList }) => (
  <>
    <Head>
      <title>GOODS CART イベントのグッズ代が計算できるWEBアプリ</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
      <link
        href='https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap&text=Goodsist'
        rel='stylesheet'
      />
    </Head>
    <Header />
    <div className={styles.container}>
      <main className={styles.main}></main>
      <div className={styles.contant_name_container}>
        <p className={styles.content_name}>{goodsList[0].content_name}</p>
        {/* <p className={styles.event_date}>2019年07月13日～</p> */}
      </div>
      <div className={styles.event_title_container}>
        <h1 className={styles.h1}>{goodsList[0].event_name}</h1>
      </div>
      <div className={styles.event_menu_container}>
        <div className={styles.event_date}>日程：日にち</div>
      </div>
      <div className={styles.event_menu_container}>
        <div className={styles.event_title_container}></div>
      </div>
      <Footer />
    </div>
  </>
)
export default Home
