/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState, useEffect, useCallback } from 'react'
import Footer from '../components/Footer'
import Header from '../components/Header'
import { supabase } from '../components/supabase'
import styles from '../styles/Home.module.css'

//イベントクラス
class Event {
  content_id: number = 0
  content_name: string = ''
  event_id: number = 0
  event_name: string = ''
}

export async function getStaticProps() {
  const { data, error } = await supabase
    .from('events')
    .select('event_id, event_name, contents(content_id, content_name)')

  const eventList: Event[] = []
  data?.map((doc) => {
    const data: Event = {
      content_id: doc.contents.content_id,
      content_name: doc.contents.content_name,
      event_id: doc.event_id,
      event_name: doc.event_name,
    }
    eventList.push(data)
  })
  type PageProps = {
    eventList: Event[]
  }
  const props: PageProps = {
    eventList: eventList,
  }

  return { props }
}
//   return {
//     props: {
//       eventList,
//     },
//   }
// }

// const Home: NextPage = ({ eventList }) => {
const Home: NextPage = ({ eventList }: props) => {
  console.log(eventList)
  return (
    <>
      <Head>
        <title>GOODS CART イベントのグッズ代が計算できるWEBアプリ</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap&text=Goodsist'
          rel='stylesheet'
        />
      </Head>
      <Header />
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>Goodsist</h1>

          <p className={styles.description}>グッズ代が計算できるWEBアプリ</p>

          <form action='https://qiita.com' method='GET'>
            <input
              className={styles.seach}
              type='seach'
              placeholder='アーティスト・イベント・作品名等で検索'
            ></input>
            <input type='submit' name='submit' value='検索' />
          </form>
          <div className={styles.grid}>
            <ul className={styles.card}>
              <h3>新しいイベント</h3>
              {eventList.map((event) => (
                <li key={event.event_id}>
                  <Link href={'event/' + event.event_id}>
                    <a>
                      {event.content_name} {event.event_name}
                    </a>
                  </Link>
                </li>
              ))}
            </ul>
            <ul className={styles.card}>
              <h3>人気なイベント</h3>
              {eventList.map((event) => (
                <li key={event.event_id}>
                  <Link href={'event/' + event.event_id}>
                    <a>
                      {event.content_name} {event.event_name}
                    </a>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </main>

        <Footer />
      </div>
    </>
  )
}

export default Home
