import { useRouter } from 'next/router'
import { supabase } from '../../../components/supabase'
import Link from 'next/link'
import styles from '../../../styles/Admin.module.css'
import Title from '../../../components/view/title'
import Head from 'next/head'
import { GetServerSideProps } from 'next'
import InputText from '../../../components/form/InputText'
import Form from '../../../components/form/Form'
import { useEffect, useState } from 'react'
import AdminHeader from '../../../components/admin/Header'
import AdminLogin from '../../../components/admin/login'
import { Events } from '../../../components/types'

// ページコンポーネントに渡されるデータ
type Props = {
  eventList: Events[]
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data, error } = await supabase
    .from('events')
    .select('event_id, event_name, items, contents(content_name)')
    .order('event_id', { ascending: false })

  const eventList: Events[] = []

  data?.map((doc) => {
    const event: any = {
      event_id: doc.event_id,
      event_name: doc.event_name,
      content_name: doc.contents.content_name,
      items: doc.items,
    }
    eventList.push(event)
  })

  return { props: { eventList } }
}
export default function Admin({ eventList }: Props) {
  const router = useRouter()

  console.log(eventList)

  return (
    <>
      <Head>
        <title>Goods List 管理者ログイン</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width,initial-scale=1.0,maximum-scale=1.0' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap&text=Goodsist'
          rel='stylesheet'
        />
        <link
          href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'
          rel='stylesheet'
        ></link>
      </Head>
      <AdminHeader />
      <div className={styles.wrapper_white}>
        <Title title='イベント一覧' />

        <Link href='events/register'>
          <a>新規登録</a>
        </Link>
        <Link href='events/csv'>
          <a>CSV新規登録</a>
        </Link>
        <ul>
          {eventList.map((event) => (
            <li>
              {event.event_id} {event.content_name} {event.event_name}{' '}
              <Link href={'events/' + event.event_id}>
                <a>編集</a>
              </Link>
              <Link href={'items/' + event.event_id}>
                <a>アイテム登録</a>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </>
  )
}
