import Link from 'next/dist/client/link'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState, useEffect, useRef, useCallback, useContext } from 'react'
import Line from '../../../public/images/line.svg'
import Twitter from '../../../public/images/twitter.svg'
import { ModalContext } from '../../components/modal/ModalContext'
import { SignUpContext } from '../../components/signup/SignUpContext'
import styles from '../../styles/Login.module.css'
import { supabase } from '../../components/supabase'
import Modal from '../../components/modal/Modal'
import InputText from '../../components/form/InputText'
import SubmitButton from '../../components/form/SubmitButton'
import { validateEmail, validatePassword, validatePassword2 } from '../../components/Validation'

export default function SignUp(): JSX.Element {
  const router = useRouter()

  const {
    openModalFlag,
    setOpenModalFlag,
    modalType,
    openModalContentFlag,
    setOpenModalContentFlag,
    setShowLogin,
    setOpenClearOverlay,
  }: any = useContext(ModalContext)

  const { setSendEmail }: any = useContext(SignUpContext)

  const [email, setEmail] = useState('')
  const [errorEmail, setErrorEmail] = useState('')
  const [validEmail, setValidEmail] = useState(false)
  const [password, setPassword] = useState('')
  const [errorPassword, setErrorPassword] = useState('')
  const [validPassword, setValidPassword] = useState(false)
  const [password2, setPassword2] = useState('')
  const [errorPassword2, setErrorPassword2] = useState('')
  const [validPassword2, setValidPassword2] = useState(false)
  const [isSubmit, setIsSubmit] = useState(false)
  const [errorSubmit, setErrorSubmit] = useState('')
  const [isButtonLoading, setIsButtonLoading] = useState(false)
  const [isNewEmail, setIsNewEmail] = useState()

  //メールアドレス入力のエラーチェック
  useEffect(() => {
    const newErrorEmail = validateEmail(email)
    setErrorEmail(newErrorEmail)
    if (email.length > 0 && errorEmail == '') setValidEmail(true)
    else setValidEmail(false)
  }, [email])

  //パスワード入力のエラーチェック
  useEffect(() => {
    const newErrorPassword = validatePassword(password)
    setErrorPassword(newErrorPassword)
    if (password.length > 0 && newErrorPassword == '') setValidPassword(true)
    else setValidPassword(false)
  }, [password])

  //確認用パスワード入力のエラーチェック
  useEffect(() => {
    const newErrorPassword2 = validatePassword2(password, password2)
    setErrorPassword2(newErrorPassword2)
    if (password2.length > 0 && newErrorPassword2 == '') setValidPassword2(true)
    else setValidPassword2(false)
  }, [password, password2])

  //全ての入力のバリデーションがtrueならボタンをアクティブにする
  useEffect(() => {
    if (validEmail && validPassword && validPassword2) setIsSubmit(true)
    else setIsSubmit(false)
  }, [validEmail, validPassword, validPassword2])

  //「確認メールを送信」ボタンを押下
  const signUp = async () => {
    if (validEmail && validPassword && validPassword2) {
      setIsButtonLoading(true)
      setOpenClearOverlay(true)

      const { error, data } = await supabase.auth.signUp({ email, password })
      if (error) {
        setIsButtonLoading(false)
        setErrorSubmit('エラーが発生しました。しばらく経ってからもう一度お試しください。')
        setOpenClearOverlay(false)
        console.log({ error })
      } else {
        console.log({ data })
        setSendEmail(email)
        setIsButtonLoading(false)
        setOpenClearOverlay(false)
        router.push({
          pathname: '/signup/submit',
        })
      }
    }
  }

  //メールアドレスの重複チェック
  // useEffect(() => {
  //   const validSignedUp = async () => {
  //     const { data: signed_up_email, error } = await supabase
  //       .from('signed_up')
  //       .select('email')
  //       .eq('email', email)
  //       .single()
  //     if (signed_up_email) {
  //       setErrorEmail('このメールアドレスは既に登録があります。')
  //       setValidEmail(false)
  //     }
  //   }
  //   validSignedUp()
  // }, [email])

  return (
    <>
      <Head>
        <title>Goodsist イベントのグッズ代が計算できるWEBアプリ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width,initial-scale=1.0,maximum-scale=1.0' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap&text=Goodsist'
          rel='stylesheet'
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.content_title}>
          <span>会員登録</span>
        </div>
        <div className={styles.form_container}>
          <div className={styles.notes}>
            当サイトは全て無料でご利用いただけます。
            <br />
            <Link href='/privacy'>
              <a target='_blank'>利用規約</a>
            </Link>
            、
            <Link href='/privacy'>
              <a target='_blank'>プライバシーポリシー</a>
            </Link>
            をお読みいただき、同意の上ご登録ください。
          </div>
          <div className={styles.input_header}>SNSアカウントで会員登録</div>
          <button className={styles.btn_login_twitter}>
            Twitterで会員登録
            <span>
              <Twitter />
            </span>
          </button>
          <button className={styles.btn_login_line}>
            LINEで会員登録
            <span>
              <Line />
            </span>
          </button>
          <div className={styles.input_header}>メールアドレスで会員登録</div>
          <InputText
            valid={validEmail}
            name='email'
            type='text'
            placeholder='メールアドレス'
            onChange={setEmail}
            error={errorEmail}
          />
          <InputText
            valid={validPassword}
            name='password'
            type='password'
            placeholder='パスワード'
            onChange={setPassword}
            error={errorPassword}
          />
          <div className={styles.input_notes}>半角英数字、8文字以上32文字以下。</div>
          <InputText
            valid={validPassword2}
            name='password2'
            type='password'
            placeholder='同じパスワードを再入力'
            onChange={setPassword2}
            error={errorPassword2}
          />
          <SubmitButton
            isSubmit={isSubmit}
            isButtonLoading={isButtonLoading}
            type='email'
            title='確認メールを送信'
            onClick={() => signUp()}
            error={errorSubmit}
          />
          <Link href='/login'>
            <a>
              <button className={styles.btn_link_signup}>ログインはこちら</button>
            </a>
          </Link>
        </div>
      </main>
      <Modal />
    </>
  )
}
