import Head from 'next/head'
import Navbar from '../../components/Navber'
import { useEffect, useContext } from 'react'
import Link from 'next/dist/client/link'
import { SignUpContext } from '../../components/signup/SignUpContext'
import { useRouter } from 'next/router'
import styles from '../../styles/Login.module.css'

export default function SignUpSubmit() {
  const { sendEmail }: any = useContext(SignUpContext)

  const router = useRouter()

  useEffect(() => {
    if (sendEmail == undefined) router.replace('/')
  }, [])
  return (
    <>
      <Head>
        <title>Goodsist イベントのグッズ代が計算できるWEBアプリ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width,initial-scale=1.0,maximum-scale=1.0' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap&text=Goodsist'
          rel='stylesheet'
        />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <div className={styles.content_title}>
          <span>会員登録</span>
        </div>
        <div className={styles.login_signup_form_container}>
          <div className={styles.notes}>
            <Link href='/privacy'>
              <a target='_blank'>利用規約</a>
            </Link>
            、
            <Link href='/privacy'>
              <a target='_blank'>プライバシーポリシー</a>
            </Link>
            をお読みいただき、同意の上登録してください。{sendEmail}
          </div>
          <div className={styles.form_login_sns}>
            {sendEmail}宛てに確認メールを送信しました。
            <br />
            24時間以内に確認メール内のリンクにアクセスし、登録を完了させてください。
            <br />
            24時間経過するとメールは無効となり、もう一度最初から登録になります。
          </div>
        </div>
      </main>
    </>
  )
}
